# Generated by Django 4.2.4 on 2023-08-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Dish name")),
                ("description", models.TextField(verbose_name="About dish")),
            ],
        ),
        migrations.CreateModel(
            name="FoodKitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Kitchen name")),
                ("description", models.TextField(verbose_name="About cooking type")),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Menu upadated date"
                    ),
                ),
                (
                    "dishes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="menu",
                        to="core.dish",
                        verbose_name="Menu dishes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Restaurant name"),
                ),
                (
                    "location",
                    models.CharField(max_length=254, verbose_name="Restaurant address"),
                ),
                (
                    "food_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="restaurant",
                        to="core.foodkitchen",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="restaurant",
                        to="core.menu",
                        verbose_name="Restaurant menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuVotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "votes_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Employee voting count"
                    ),
                ),
                (
                    "voting_date",
                    models.DateTimeField(auto_now=True, verbose_name="Voting date"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.menu",
                        verbose_name="Voting menu",
                    ),
                ),
            ],
        ),
    ]
