# Generated by Django 4.2.4 on 2023-08-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeVotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employeevotes",
                        to="core.employee",
                    ),
                ),
                (
                    "menu_vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employeevotes",
                        to="core.menuvotes",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menuvotes",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="menu_votes",
                through="core.EmployeeVotes",
                to="core.employee",
                verbose_name="employee who votes",
            ),
        ),
    ]
